### ISSUE TITLE
use phone, the menu cannot automatically slide to position

### ISSUE THREAD

**Issue by saberc8** [logotip4ik/MyOwnWebSite-V2#141]
When I use my phone, the menu cannot automatically slide to position, but Chrome's phone mode debugging is possible

**Comment by logotip4ik** [comment]
Can you provide some screenshots or video ?

I am using Firefox/Chrome on Android 13 and it seems to work fine

**Comment by saberc8** [comment]
I use iphone12，it can‘t work

**Comment by saberc8** [comment]
Maybe it is bug of locomotive-scroll. [issues](https://github.com/locomotivemtl/locomotive-scroll/issues/329)

**Comment by saberc8** [comment]
Maybe it is bug of locomotive-scroll. [issues](https://github.com/locomotivemtl/locomotive-scroll/issues/329)

**Comment by logotip4ik** [comment]
<img width="250" src="https://user-images.githubusercontent.com/56201308/227302124-a498240d-d400-457b-8b74-ce6557bb6083.jpg">

On iPhone 11 seems to work fine. Yeah, the animation is a bit broken but the menu still can be accessed
