### ISSUE TITLE
Blank Screen when Javascript Disabled

### ISSUE THREAD

**Issue by michael-azogu** [logotip4ik/MyOwnWebSite-V2#75]

**Comment by logotip4ik** [comment]
Hello, nice to meet you here!

Thank you for opening an issue, but this project was never meant to run without js. The website build with [Nuxt](https://github.com/nuxt/framework) which is a JS framework, + almost every component requires [gsap](https://greensock.com/gsap/) to correctly display the content, another tool is [three.js](https://github.com/mrdoob/three.js) which creates background animation. This is just not that type of a website that can or should support usage without js 🤷‍♂️
